### ISSUE TITLE
error in installation

### ISSUE THREAD

**Issue by GoogleCodeExporter** [dseeliger/pmx#2]
```
What steps will reproduce the problem?
1. Installing pmx @ mac
2.
3.

What is the expected output? What do you see instead?
running install
running build
running build_py
creating build
creating build/lib.macosx-10.9-intel-2.7
creating build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/__init__.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/atom.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/atomselection.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/builder.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/chain.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/cpp.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/ffparser.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/forcefield.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/forcefield2.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/futil.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/geometry.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/histogram.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/library.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/model.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/molecule.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/mutdb.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/ndx.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/odict.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/options.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/parser.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/rotamer.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/tCNC.py -> build/lib.macosx-10.9-intel-2.7/pmx
copying pmx/xtc.py -> build/lib.macosx-10.9-intel-2.7/pmx
running build_ext
building 'pmx/_pmx' extension
creating build/temp.macosx-10.9-intel-2.7
creating build/temp.macosx-10.9-intel-2.7/src
cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os 
-pipe -fno-common -fno-strict-aliasing -fwrapv -mno-fused-madd -DENABLE_DTRACE 
-DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g 
-fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 
-pipe -Isrc 
-I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c 
src/Geometry.c -o build/temp.macosx-10.9-intel-2.7/src/Geometry.o
clang: error: unknown argument: '-mno-fused-madd' 
[-Wunused-command-line-argument-hard-error-in-future]
clang: note: this will be a hard error (cannot be downgraded to a warning) in 
the future

What version of the product are you using? On what operating system?
MacOs 10.9.2, 3.1 GHz Intel Core i7
8 GB 1600 MHz DDR3

Please provide any additional information below.

Although I have installed all needed packages I couldm't Install pmx 
```

Original issue reported on code.google.com by `edgarmix...@gmail.com` on 13 Mar 2014 at 3:52

**Comment by RasmusFonseca** [comment]
I have problems with installation on mac as well. I have python installed through homebrew and succesfully run the install

    MacBook:~/Programs/pmx $ sudo python setup.py install
    Password:
    running install
    running build
    running build_py
    running build_ext
    running install_lib
    running install_data
    running install_egg_info
    Removing /usr/local/lib/python2.7/site-packages/pmx-1.1.0dev-py2.7.egg-info
    Writing /usr/local/lib/python2.7/site-packages/pmx-1.1.0dev-py2.7.egg-info 

But when importing in python i get:

    MacBook:~/Programs/pmx $ python
    Python 2.7.11 (default, Feb 12 2016, 14:06:05)
    [GCC 4.2.1 Compatible Apple LLVM 7.0.2 (clang-700.1.81)] on darwin
    Type "help", "copyright", "credits" or "license" for more information.
    >>> import pmx
    Traceback (most recent call last):
      File "<stdin>", line 1, in <module>
      File "pmx/__init__.py", line 45, in <module>
        from atom import *
      File "pmx/atom.py", line 51, in <module>
        import _pmx as _p
    ImportError: No module named _pmx

**Comment by dseeliger** [comment]
Hi Rasmus,

I think the problem is that you start python in the same folder where the pmx source code is. Then it imports pmx from the local path. When you start python somewhere else the problem should be solved.
On my mac it runs without problems.

Best,
Daniel
